### ISSUE TITLE
Cannot compile : "error C2039: ‘reset’: is not a member of ‘REL::Module’"

### ISSUE THREAD

**Issue by Zouizoui78** [ersh1/TrueHUD#2]
Hi there ! I'm very new to Skyrim modding, SKSE, Commonlib, etc but I am trying to compile your TrueHUD plugin. Long story short I wanted to try and implement some changes by myself to learn a bit about how this kind of plugins work.

So as I said I'm trying to compile the plugin but after following the steps in the readme it fails at the build step.
CommonLib gets compiled just fine (I get a CommonLibSSE.lib file) but then the TrueHUD plugin itself fails with the following error :

```
C:\build\TrueHUD\src\main.cpp(96,15): error C2039: ‘reset’: is not a member of ‘REL::Module’ [C:\build\TrueHUD\build\sr 
c\TrueHUD.vcxproj]
```
I have all the dependencies installed and the environment variables set.

Any idea of what the issue might come from ?

**Comment by ersh1** [comment]
It's currently a workaround for a bug in CommonLibSSE-NG, you need to edit REL/Relocation.h in the recent CommonLibSSE-NG and move the `static void reset()` outside of the `#ifdef ENABLE_COMMONLIBSSE_TESTING` - just move the `#endif` so it's above it. I've done this manually without forking it as it's just a tiny change, and it's going to be fixed in NG eventually.
